name: secp256k1cipher
description: Encrypt and decrypt data use secp256k1
version: 0.0.1
author: Alexander.Li<superpowerlee@gmail.com>
homepage: https://github.com/ipconfiger/secp256k1Cipher

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  pointycastle: '>=1.0.1 <1.0.2'

dev_dependencies:
  test: '>=0.12.30 <1.4.0'
